package com.cocktail.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.springframework.stereotype.Component;

import java.util.List;

//lombok annotations
//annotation helps to generate toString(), equals(), hashcode(), getter(), setter()
@Data
//annotation helps to generate a no-argument constructor
@NoArgsConstructor
//annotation helps to generate a constructor with 1 parameter for each field in the class
@AllArgsConstructor
//annotation helps to implement the builder design pattern
//usage can be seen in BookService.java
@Builder
//spring stereotype annotation
@Component
@DynamoDBTable(tableName = "cocktail")
public class Cocktail {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    String id;
    @DynamoDBAttribute
    String name;
    @DynamoDBAttribute
    String description;
    @DynamoDBAttribute(attributeName = "ingredients")
    List<String> ingredients;
    @DynamoDBAttribute
    String created;
    @DynamoDBAttribute
    String modified;
}

